import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");

  const handleSubmit = (event) => {
  event.preventDefault();

  if (firstName === "") {
      toast.error("Enter first Name");
  } else if (lastName === "") {
      toast.error("Enter Last Name")
  } else if(phone > 10000000000 || phone < 999999999) {
      toast.error("Enter Valid Mobile no")
  }else if(email === ""){
      toast.error("Enter email")
  }else{
      Data.firstName = firstName;
      Data.lastName = lastName;
      Data.email = email;
      Data.phone = Number(phone) ;
  
      CreateUser()
  }
  
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://stijndv.com" />
        <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
      </Head>
      <main className={styles.main}>


      <div className={styles.center}>
          
          <div className={styles.thirteen}>
            <p>ITSA</p>
          </div>
        </div>
        {/* <div className='app__form'>

          <div className='form__header'>
              <p className='step__count'><span style={{color: '#ddab6c'}}>1</span>/4</p>
              <p className='form__name'>Create Account</p> 
          </div>

          <form onSubmit={handleSubmit}>
              <div className='form__item'>            
                  <p>First Name</p>
                  <input type="text" value={firstName} onChange={(e) => setFirstName(e.target.value)}/>
              </div>
              <div className='form__item'>            
                  <p>Last Name</p>
                  <input type="text" value={lastName} onChange={(e) => setLastName(e.target.value)}/>
              </div>
              <div className='form__item'>            
                  <p>Email</p>
                  <input type="email" value={email} onChange={(e) => setEmail(e.target.value)}/>
              </div>
              <div className='form__item'>            
                  <p>Phone</p>
                  <input type="tel" value={phone} onChange={(e) => setPhone(e.target.value)}/>
              </div>


              <div className='form__submit'>
                  <input type="submit" value='Create Account'/>
              </div>

          </form>
          </div> */}

        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  )
}
